apiVersion: v1
kind: Secret
metadata:
  name: pv-data-backup-secrets
type: Opaque
data:
  AWS_S3_ACCESS_KEY_ID: {{ .Values.secrets.AWS_S3_ACCESS_KEY_ID }}
  AWS_S3_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_S3_SECRET_ACCESS_KEY }}
  ENCRYPTION_KEY: {{ .Values.secrets.ENCRYPTION_KEY }}
